### ISSUE TITLE
Account Login / Creation

### ISSUE THREAD

**Issue by kernelkind** [damus-io/notedeck#113]
The current figma design for account login / creation:
![Set your account](https://github.com/damus-io/notedeck/assets/8139906/857e5d65-c4c7-4cbd-952e-d830ebd29edd)

**Comment by kernelkind** [comment]
When the account management view ['add account' button](https://github.com/damus-io/notedeck/issues/77#issuecomment-2192083099) is pressed, the user will be presented with the account login/creation view.

The design shows the account login view welcoming the user as if they are brand new to the app. But since we're going to drop the user right into the app without a welcome screen #112, I don't think it makes sense to welcome them after they've been using the app for a bit. Plus, they can always add more accounts at a later time.

Should we come up with a design that makes more sense with the default deck idea? I propose just using the global popup window to present the contents of the 'window' at the center of the current account login / creation figma design.

@robagreda what do you think?

**Comment by jb55** [comment]
this is doneish
