### ISSUE TITLE
Profile pictures in column header

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#12]
I saw this on tweetdeck and thought it was a decent way to display which account a panel is for (@damusapp at the top)

Imagine having DMs/notifications for both your corporate account and personal account on the same screen for instance.

Instead of the account name, we could perhaps put the PFP instead? @robagreda @karnagebitcoin

I also like the grip icon for moving it around once we have that.

![Mar28-135814](https://github.com/damus-io/notedeck/assets/45598/03f7c517-0e91-443f-9da7-ffb54b3887c0)

**Comment by jb55** [comment]
cc @kernelkind to see what I mean about per-column accounts

**Comment by kernelkind** [comment]
I think this is an interesting idea. Instead of one account being associated with the whole viewing area of the app,  there is one account per panel. 

I haven't used tweetdeck before, but I think there should be a place to store accounts. Then, when the user wants to add a new panel, they can select the account from their storage that they want the panel to be associated with

**Comment by jb55** [comment]
Re: (https://github.com/damus-io/notedeck/issues/12)

On Thu, Mar 28, 2024 at 11:13:31AM GMT, kernelkind wrote:
>I think this is an interesting idea. Instead of one account being
>associated with the whole viewing area of the app,  there is one
>account per panel.

One thing we want to be global to the viewing area is a user's mutelist.
This is where you might need an initial login account anyways.

Your mute list would apply to other peoples timelines by default, but
maybe this would be configurable otherwise it wouldn't 100% reflect
their timeline.

>I haven't used tweetdeck before, but I think there should be a place to
>store accounts. Then, when the user wants to add a new panel, they can
>select the account from their storage that they want the panel to be
>associated with

yeah that's the idea, but keep in mind you could in theory use any
profile from your profile database and add it as a panel, like your
friends notifications and timelines to break out of your bubble, but
the accounts in your current login manager would likely be the first
N options.

For panel/lists state, I was thinking there should be some kind of
"profile" configuration. Which may be as simple as a nostr note or json
file that describes it.

I am definitely leaning towards having an encrypted note for client
configuration options. One annoying thing we had on damus was that a
users settings would get wiped out every time they reinstalled the app.
If your panel state, login pubkey set, and client settings were all in
an encrypted note, this would be cool!

**Comment by jb55** [comment]
On Mon, Apr 01, 2024 at 06:38:54AM -0700, Karnage wrote:
>> I also like the grip icon for moving it around once we have that.
>
>Wondering if this can be shown on hover over column heading. Less distracting, equally useful?
>
>https://cln.sh/rrpd1Gz8

nice, good idea.

**Comment by jb55** [comment]
Some initial egui-nav work on this to enable custom title rendering:

- https://github.com/damus-io/egui-nav/pull/5
