### ISSUE TITLE
Onboarding: create default user if we have none

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#132]
If we don't have a user account, we should randomly generate some keys! The user can always add their own account afterwards if they have one already.

We need a user to create the initial deck list with the demo deck inside:

- https://github.com/damus-io/notedeck/issues/133

**Comment by jb55** [comment]
you going to take this one @kernelkind  ?

**Comment by alltheseas** [comment]
> If we don't have a user account, we should randomly generate some keys

Default can simply be @jb55 's npub. View as / demo mode should be clearly displayed.

**Comment by alltheseas** [comment]
@robagreda to explore onboarding by 


- [ ] testing notedeck pre-alpha release / build
- [ ] adding high value guardrails (e.g. "you are testing notedeck using Will's npub. to create a nostr profile, or log in with your keys go here"
