### ISSUE TITLE
Thread view

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#135]
We should do something similar to damus ios here with the chat threads

**Comment by alltheseas** [comment]
- [ ] Clicking on the "comment" icon in a note causes notedeck to crash

![commentcrash](https://github.com/user-attachments/assets/7d6010fc-a11c-43c1-b8e8-0eb7c49c6880)

**Comment by jb55** [comment]
what commit are you on?

**Comment by alltheseas** [comment]
Is there a way to check in app? 

I downloaded the latest earlier today

![image](https://github.com/user-attachments/assets/f2178625-e407-4ad8-9aea-dafa5906795a)

**Comment by alltheseas** [comment]
Just re-downloaded latest (06028ba) to double check behavior. Confirmed the crash on click on comment.

**Comment by alltheseas** [comment]
> * [x]  Clicking on the "comment" icon in a note causes notedeck to crash
> 

resolved on [1c8b68c]

![Screenshot from 2024-07-25 12-10-16](https://github.com/user-attachments/assets/47c142e9-8708-4616-a8e1-1c070df20546)

**Comment by alltheseas** [comment]
- [ ] when I log in with my nsec, do not show me @jb55 PFP in reply view. Show my PFP instead.

![Screenshot from 2024-07-25 13-35-32](https://github.com/user-attachments/assets/d8ce0448-a462-4057-ae6d-6ecf624e2347)

**Comment by alltheseas** [comment]
![Screenshot from 2024-07-25 14-12-01](https://github.com/user-attachments/assets/a036f88a-9779-478d-9c82-c2bb2c42e2b8)

not sure what this is - some embedded media?

**Comment by alltheseas** [comment]
also see https://github.com/damus-io/notedeck/issues/198

**Comment by alltheseas** [comment]
nostr: handler tracking issue: https://github.com/damus-io/notedeck/issues/62

**Comment by jb55** [comment]
Made lots of progress on:

- https://github.com/damus-io/notedeck/pull/155

## Progress

- [x] Local subscriptions working, including re-using the same subscription if we have the same thread open twice
- [x] Local thread lookup and updating whenever you revisit the thread
- [ ] Remote subscriptions
- [ ] Reply paths
