### ISSUE TITLE
Repurpose web subscribe flow to notedeck

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#157]

**Comment by alltheseas** [comment]
fyi @danieldaquino - not sure if this is all yours, or @jb55 can handle

**Comment by jb55** [comment]
What does this mean

**Comment by alltheseas** [comment]
Previously purple checkout on damus website only directed to iOS.

With new update, correct if I am wrong @danieldaquino there are notedeck downloadable files

**Comment by danieldaquino** [comment]
> Previously purple checkout on damus website only directed to iOS.
> 
> With new update, correct if I am wrong @danieldaquino there are notedeck downloadable files for non-iOS OS

Yep! That sounds correct
