### ISSUE TITLE
Conceive user account

### ISSUE THREAD

**Issue by kernelkind** [damus-io/notedeck#164]
There should be a conception to represent a user's account to be able to save(#110)/load(#112) to/from disk. This should allow for easy access to multiple accounts in notedeck and android.

I propose:
```
struct SerializableUserAccount {
    key: nostr_sdk::secp256k1::SecretKey,
    relays: Vec<String>,
    // TODO: variable for bookmarks
}
```
and
```
struct UserAccount {
    key: nostr_sdk::Keys,
    pool: RelayPool,
}
```

Then in `app.rs` `Damus` would hold a variable `accounts: Vec<UserAccount>`. When a column needs to access a user account's pub/priv key or relays, it would access the respective `Damus::accounts`

**Comment by alltheseas** [comment]
@kernelkind is this one done?
