### ISSUE TITLE
log in with npub / demo mode / viewer mode

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#178]
- [x] log in with npub
- [ ] when app is first started, display "not logged in banner"
- [ ] if logged in with npub, display "logged in with npub; cannot write" banner at top of screen  (see https://github.com/damus-io/damus/issues/1153)
- [ ] if logged in with npub, display "logged in with npub; cannot write" banner at top of screen" on account switcher screen (see mockup below)

**Comment by alltheseas** [comment]
mockup example label in account switcher ![cannotwrite](https://github.com/user-attachments/assets/c44d742b-5d5e-4681-bad5-c8cda5c72ba6)

**Comment by alltheseas** [comment]
log in with npub works

**Comment by alltheseas** [comment]
tentatively adding to alpha @jb55 as
1) logging in with npub/read only mode is very powerful
2) notedeck allows monitoring of a "company" npub like damus npub by team members, without the need to share a nsec
3) iOS shows that people are confused when they accidentally or purposefully log in with npub, and cannot e.g. write, react etc.

**Comment by jb55** [comment]
this seems done?
