### ISSUE TITLE
not opening

### ISSUE THREAD

**Issue by codegod100** [damus-io/notedeck#28]
I built with wgpu and thought that was the issue then removed wgpu from config toml and it's using glow but still closes immediately with no errors and no window

running on debian 12

**Comment by jb55** [comment]
can you show the output of `RUST_LOG=debug cargo run`

**Comment by jb55** [comment]
I'm guessing this is related to

- #42

**Comment by jb55** [comment]
can you comment and uncomment these lines and see if it helps?

```
eframe = { version = "0.27.2", default-features = false, features = [ "glow", "wgpu", "android-native-activity" ] }
#eframe = { version = "0.27.2", default-features = false, features = [ "glow", "android-native-activity" ] }
```

**Comment by jb55** [comment]
I have to do this on my nixos laptop, I haven't yet fixed 

- #42

**Comment by jb55** [comment]
very weird... must be a wayland issue? I have not tested with wayland.

**Comment by jb55** [comment]
On Wed, May 15, 2024 at 10:59:00PM GMT, hellodword wrote:
>Still no luck on X11, in a new nixos vm, with the commit https://github.com/damus-io/notedeck/commit/0e0e5d0eaa74e17ce7dfa477969f05b5ac009d93:
>
>See: https://gist.github.com/hellodword/e368c8e07f4a661c4ed0281d117fc61d

can you run other egui demos in the egui repo?

**Comment by jb55** [comment]
On Thu, May 16, 2024 at 07:19:56PM GMT, hellodword wrote:
>It seems that I've fixed it on Sway, I'll push the changes (wayland) to #57

awesome, thank you!

**Comment by jb55** [comment]
wgpu has been updated, let me know if you still run into issues on wayland

**Comment by jb55** [comment]
I think there is a still a wayland issue
