### ISSUE TITLE
Help button

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#296]
Now that notedeck is a desktop OS app, we can have a 'Help'  button.

Example from signal desktop app:

![signalmenu](https://github.com/user-attachments/assets/b0922a63-9c91-456c-a40c-59aa35c960ce)

Could be:
-> release notes
-> report a bug
-> contact us (purple members only)
-> purple members early release group (purple members only)
-> subscribe

**Comment by jb55** [comment]
Initial version is in
