### ISSUE TITLE
Post reply box

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#3]
Where do we put the reply box? Should we just pop it up like we do on Damus-iOS?

For notedeck should we put it inline or as a popup as well. Lots of design decisions to be made here.

It doesn't look like we have a design for this in the figma @robagreda

**Comment by jb55** [comment]
Some other examples in the wild: tweetdeck does a popup

![](https://cdn.jb55.com/s/73606f6fdd3d854e.png)

**Comment by robagreda** [comment]
![CleanShot 2024-03-13 at 08 01 36@2x](https://github.com/damus-io/notedeck/assets/3373850/d482ea7e-4a4f-4d1d-9244-0b57a77d31fb)
I have it inline here, do you think is best to pop it out? Like twitter?

**Comment by robagreda** [comment]
Will be designing that today. The post box is inline now, but I don't think the reply box is a good idea to have it inline. I think I will just pop it out.

**Comment by jb55** [comment]
On Wed, Mar 13, 2024 at 07:03:04AM -0700, Roberto wrote:
>![CleanShot 2024-03-13 at 08 01 ***@***.***(https://github.com/damus-io/notedeck/assets/3373850/d482ea7e-4a4f-4d1d-9244-0b57a77d31fb)
>I have it inline here, do you think is best to pop it out? Like twitter?

that's for posting, I was thinking specifically the reply action which
is different.

**Comment by robagreda** [comment]
https://www.figma.com/file/aONNEWCxHlckZJq0lHyxrN/Notedeck?type=design&node-id=663%3A1836&mode=design&t=jBr2dklRp3XeJzMz-1

I designed this solution, any thoughts?

**Comment by jb55** [comment]
On Wed, Mar 13, 2024 at 08:18:53AM -0700, Roberto wrote:
>https://www.figma.com/file/aONNEWCxHlckZJq0lHyxrN/Notedeck?type=design&node-id=663%3A1836&mode=design&t=jBr2dklRp3XeJzMz-1
>
>I designed this solution, any thoughts?

looks amazing!

**Comment by jb55** [comment]
this is done
