### ISSUE TITLE
blank contacts column when started with npub

### ISSUE THREAD

**Issue by ksedgwic** [damus-io/notedeck#316]
I believe this behavior started between `8e32f757f0d` and `2208e6872`

This displays both columns:
```
cargo run -- --nsec <my-nsec-here> -c contacts -c notifications
```

This only displays the second column, first is blank:
```
cargo run -- --npub npub1s5rq2ztdh76shy578znvympa2mzz2vjushs9mc5mwkdupewke67qeuf7u3 -c contacts -c notifications
```

I believe it used to show both columns ...

**Comment by alltheseas** [comment]
@ksedgwic investigating. 

Ken - are you able to self-assign?

**Comment by ksedgwic** [comment]
I am able to self-assign (ie #278), but not sure I have insight into this issue yet.
