### ISSUE TITLE
Don't render all notes at once

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#32]
To improve performance across the board, we need to switch to a method of rendering notes which only renders the notes that are on screen. We start to dip below 144fps at around 400notes. We really only need to render maybe 20-30 notes. This should give us an insane amount of performance wiggle-room for lower performance devices.

There are a few approaches we can take:

- [egui_extra's TableBuilder](https://docs.rs/egui_extras/latest/egui_extras/struct.TableBuilder.html) by @emilk - This is a built-in way to do variable-height collections, but it seems a bit hard-coded to be table-like
- [egui_virtual_list](https://docs.rs/egui_virtual_list/latest/egui_virtual_list/) or [egui_infinite_scroll](https://docs.rs/egui_infinite_scroll/latest/egui_infinite_scroll/) an alternative approach by @lucasmerlin but seems to have a few baked in assumptions which I'm not sure about
- A custom approach my @mikedilger for calculating space ahead of time and filling in space to ensure scrollbar is accurate. it's simple and I like it, but maybe it's not a general solution for arbitrary views?
- Roll our own, maybe we can take a crack at it (NIH) ?

**Comment by lucasmerlin** [comment]
Hi, curious what baked in assumptions you mean? I tried to make egui_virtual_list as flexible as possible (as long as you scroll vertically)

**Comment by jb55** [comment]
@lucasmerlin  I was just looking at infinite_scroll and some of the loading logic. I will try virtual list as that looks a bit more general.

**Comment by jb55** [comment]
@lucasmerlin holy hell that works insanely well and it works perfectly. I am impressed
