### ISSUE TITLE
Use user's relay list

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#332]
We should fetch a users relay list if we don't have it. We can use our current hardcoded list as our bootstrap list.

Some open questions:

- What relay list should we use when we have multiple users?
- We could use a union of the lists for the alpha release
- Future releases may add them all as active connections, and simply subscribe to the correct ones based on context?

**Comment by ksedgwic** [comment]
On startup, we use the bootstrap relay list to try and fetch the users `k:10002` record.

Do we block other progress while we wait?  Or should we proceed w/ setting up the timelines w/ the bootstrap list while we wait?

**Comment by ksedgwic** [comment]
Another question: do we union in the `k:3` relays with the `k:1002`?  Are there other sources of relays I should be considering?

**Comment by alltheseas** [comment]
@ksedgwic has a proposal for a method

@jb55 to review soon :tm: 

@ksedgwic advises just thumbs up is sufficient; complete review not needed. Hardening work remainaing, plenty to do with thumbs up.

**Comment by alltheseas** [comment]
@ksedgwic added:

-bootstrapping (if nothign else is working)
-local relays will always be used. set added with advertised relays (solely from network)
-forced relays - if see in command; doesnt update

**Comment by alltheseas** [comment]
@ksedgwic maybe there is a need for "fixed relays" down the road

**Comment by alltheseas** [comment]
@jb55 - overlapping relays sets - might make sense to have transiently maintained relays list. maintain relays, but dont reconenct all the time.

Multiple profiles may require use of different relays.

@ksedgwic - when adding subscription over available relays - "this subscription does not go over this relay". 

Subscriptions need an additional argument - "what kind of subsription is this - read, write etc."

Easy to add

**Comment by jb55** [comment]
Initial version in:

- f00a67ab2cd83049af4d4862e12b5609af301459
