### ISSUE TITLE
Minor issue with coloring username in ProfilePreview

### ISSUE THREAD

**Issue by kernelkind** [damus-io/notedeck#35]
https://github.com/damus-io/notedeck/blob/69054d71ca020ad74cc5d99d7f3064e0f2a5f5db/src/ui/profile/preview.rs#L98

I don't think the color should be set like this because it will not change when the user changes their theme. The color should be set using some `ui.visuals()...`. I didn't make any colors in `colors.rs` public to discourage this. @jb55 

I'm aware though that `Visuals` is a bit limiting, we may need to think of a custom solution in the future. Not high priority

**Comment by jb55** [comment]
yeah I plan on cleaning this up once we have our colors figured out and we can switch to themes for these.
