### ISSUE TITLE
when I log in "??" displayed as my name

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#356]
true both for
1) logging in with nsec
2) creating new keys

**Comment by alltheseas** [comment]
should there be:
1) a "loading" UI affordance, if keys are not new & profile info exists?
2) for new keys - a prompt to set up profile?

**Comment by jb55** [comment]
I think we just need to include local accounts into the unknown id search system

**Comment by jb55** [comment]
added this to my list of things to do today. should be easy
