### ISSUE TITLE
record vanessa test

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#374]
-record screen
-record vanessa (if she allows)
while note providing any guidance

### Tasks 

https://github.com/damus-io/notedeck/issues/419#issuecomment-2471524676

**Comment by alltheseas** [comment]
added to alpha milestone https://github.com/damus-io/notedeck/milestone/1

**Comment by kernelkind** [comment]
>     * [ ]  -like
>     * [ ]  -tag someone
>     * [ ]  -view video

we don't have these features yet

**Comment by alltheseas** [comment]
> > ```
> > * [ ]  -like
> > * [ ]  -tag someone
> > * [ ]  -view video
> > ```
> 
> we don't have these features yet

thanks, added
https://github.com/damus-io/notedeck/issues/365

@jb55 some people suggested OBS for recording the Vanessa test, others zoom. You probably know better than me what is good for recording.

Just remember, don't help Vanessa, or talk to her. Just sit silently in pain while she tries to use the software, and make sure you are recording the screen, mouse, and her face :smile:

**Comment by alltheseas** [comment]
tasks here https://github.com/damus-io/notedeck/issues/419#issuecomment-2471524676
