### ISSUE TITLE
add single hashtag column

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#375]
For instance #photography

https://damus.io/nevent1qqsvtk6xp53hm8pjlwh78nqk3tdd0u5m7ymncpaqg6u86w32q4fcjgspzfmhxue69uhhqatjwpkx2urpvuhx2ucpzpmhxue69uhkummnw3ezuamfdejsz9thwden5te0v4jx2m3wdehhxarj9ekxzmnyqyd8wumn8ghj7cmpw3ehgunj9eehwctjd4ehgu3wvdhk6rqgyfj

**Comment by alltheseas** [comment]
> just merged hashtag columns to notedeck! 

https://damus.io/nevent1qqswmpq7k0r8uhqtnrmlm632xtekds8zw558txralv952hxhjvpvqpspz3mhxue69uhhyetvv9ujuerpd46hxtnfduqs6amnwvaz7tmwdaejumr0dsq35amnwvaz7tmwdaehgu3wdaexzmn8v4cxjmrv9ejx2asprpmhxue69uhhwetvvdhk6efwdehhxarj9emkjmn9av7e2v

**Comment by kernelkind** [comment]
added in 792abf11d77e5989497a893f76d58b6ca1c4a964
