### ISSUE TITLE
Use user's mutelist

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#382]
Right now we do not process and use a user's mute lists. We should.

It should apply to globally, even on timelines that follow other people's accounts.

**Comment by alltheseas** [comment]
looking at someone else's list/edge mute list test case: https://github.com/nostrability/nostrability/issues/116

**Comment by alltheseas** [comment]
@ksedgwic investigating this

**Comment by jb55** [comment]
Should be added in 

- d5956319660823d86d875f17144a4258c7f4b690
