### ISSUE TITLE
"Contacts" column title incorrect after switching users

### ISSUE THREAD

**Issue by kernelkind** [damus-io/notedeck#397]
When I have a "Contacts" or "Notifications" column (which shows the contacts or notifications for my current account) and then switch to a different account, I would expect the title to change to "___'s Contacts" or "___'s Notifications". 

What currently happens is the column stays "Contacts" or "Notifications" but the content remains the previous account's feed.

**Comment by jb55** [comment]
Fixed via new pfp columns?
