### ISSUE TITLE
Roberto design help for notedeck launch + website changes for notedeck

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#418]
Notedeck launch: november 30th

@robagreda these are the latest versions of website:

HOMEPAGE: https://staging.damus.io/
NOTEDECK: https://staging.damus.io/notedeck/

what would you like @danieldaquino to fix on the website in anticipation of notedeck launch?

Consider adding some section (e.g. FAQ/other) for what is supported on day one, and what is not supported https://github.com/damus-io/notedeck/issues/365

-------

**Design file:** https://www.figma.com/design/aONNEWCxHlckZJq0lHyxrN/Notedeck?node-id=2943-55304&node-type=frame

**Comment by danieldaquino** [comment]
New website released!
