### ISSUE TITLE
add nip-05 example in login view

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#441]

**Comment by kernelkind** [comment]
<img width="911" alt="login_text" src="https://github.com/user-attachments/assets/435392b2-33cd-4300-9cec-87ca724c763a">

@alltheseas Are you referring to this text? What would you like to replace it?

**Comment by alltheseas** [comment]
@kernelkind - yes - submitting PR shortly

**Comment by kernelkind** [comment]
add info 'i' next to the "enter your key" text. On hover it will display a hint about nip05 and keys in general. then the textedit hint text can be simple like "Enter your key here..."

<img width="509" alt="text_info" src="https://github.com/user-attachments/assets/47c0933b-d577-4524-b85d-4028074c2271">
