### ISSUE TITLE
Include version commit hash in UI

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#449]
This will be useful for debugging user issues, especially when we start pushing manual updates.

**Comment by alltheseas** [comment]
> Could also be included in the email

Ideally this is automagically included in the draft email, so that the user does not have to manually find this info :muscle:

**Comment by jb55** [comment]
On Mon, Nov 18, 2024 at 04:40:19AM GMT, kernelkind wrote:
>I think it would make sense to put it in the support view. Could also be included in the email

yup

**Comment by kernelkind** [comment]
added in 9cfae313aa1c2c16a7b4d69150f3804f08d7cfd0
