### ISSUE TITLE
Missing hastag icon

### ISSUE THREAD

**Issue by robagreda** [damus-io/notedeck#490]
![CleanShot 2024-11-27 at 11 43 00@2x](https://github.com/user-attachments/assets/3f2228a0-6ea7-4993-8823-828598096e9c)

**Comment by kernelkind** [comment]
@robagreda can you add hashtag as an option in the figma design?

<img width="308" alt="image" src="https://github.com/user-attachments/assets/454ca217-a428-43aa-ba05-d37455c127bc">

 For now we're just converting the icon to a png and using that in the app. That would make this an easy fix
