### ISSUE TITLE
Add Windows ARM cross build

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#506]

**Comment by alltheseas** [comment]
"I did it but I’m running into the same issue with “ring” as I run to with gossip & lume, Mike told me it had something to do with ring & arm64"

**Comment by ser-sleepy** [comment]
👀

**Comment by jb55** [comment]
so the build is technically working but it seems like its still not starting up for sleepy.

we should get logging working so we can tell what's going on:

- #572 

@kernelkind set this up, maybe it broke somewhere. might need tests for this.

**Comment by jb55** [comment]
Continuing the issue here:

- #573
