### ISSUE TITLE
Simplify UI: when I log in, auto-remove "accounts" view

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#512]
Simplify UI: when I log in, auto-remove "accounts" view
Replace instead with: home npub/nsec/nip-05 view, universe view etc

![Frame 36](https://github.com/user-attachments/assets/9d30b069-3a44-4a0c-8c6e-a03f9383949b)

**Comment by kernelkind** [comment]
fixed in 475314da75fada4f38dc13c1c73f8175e5be34ad I believe
