### ISSUE TITLE
"replying to" text font size is too small

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#513]
![image](https://github.com/user-attachments/assets/659ee59d-a115-407b-9bc8-5d8bb3fecdbb)

Usabilit tester advised expects to be able to increase font size

**Comment by alltheseas** [comment]
could be fixed by user app level font settings https://github.com/damus-io/notedeck/issues/514

**Comment by jb55** [comment]
you can increase font size with Ctrl/Cmd +
