### ISSUE TITLE
Can't build the aarch64 apk on amd64

### ISSUE THREAD

**Issue by hellodword** [damus-io/notedeck#54]
With the latest commit https://github.com/damus-io/notedeck/commit/95f8623c4138bd42c767a7f14064494beceb41d9 :

`RUST_LOG=debug cargo apk build --target x86_64-linux-android` works

`RUST_LOG=debug cargo apk build --target aarch64-linux-android` fails:

```
  = note: ld: error: /nix/store/8f10pxi30lvkdjrkzfw5gzz4rzia8163-openssl-3.0.13/lib/libssl.so is incompatible with aarch64linux
          ld: error: /nix/store/8f10pxi30lvkdjrkzfw5gzz4rzia8163-openssl-3.0.13/lib/libcrypto.so is incompatible with aarch64linux
          clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jb55** [comment]
crap, I'm guessing this is because of our switch to reqwest @kernelkind , maybe we need to revert this

**Comment by jb55** [comment]
Should be fixed!

**Comment by jb55** [comment]
I'm surprised by the sheer number of issues you are running into. this builds on my macbook, nixos desktop with gpu, nixos laptop with intel, and 2 different android phones. I only have run into issues with 32-bit android systems:

- https://github.com/damus-io/nostrdb/issues/29
