### ISSUE TITLE
Is notedeck the future of damus?

### ISSUE THREAD

**Issue by hellodword** [damus-io/notedeck#55]
I use damus on iOS, it's pretty cool. And I found notedeck when I was searching for "desktop nostr client" today.

I noticed it contains Android, so I'm curious, what's notedeck? A desktop version of damus or the next generation of damus or a totally standalone project?

**Comment by jb55** [comment]
Yes, notedeck is what damus iOS should have been, it's the future tech stack for damus and works on all platforms (windows soon). It's unlikely it will replace the iOS version because it lacks the native iOS feel, but it shares the heart/engine of notedeck (nostrdb).

**Comment by jb55** [comment]
On Wed, May 15, 2024 at 09:43:11AM GMT, hellodword wrote:
>I use damus on iOS, it's pretty cool. And I found notedeck when I was searching for "desktop nostr client" today.

curious how you found notedeck with a search? I can't seem to find this when I google it.
