### ISSUE TITLE
Quick exit on nixos with sway

### ISSUE THREAD

**Issue by nyonson** [damus-io/notedeck#609]
Attempting to run on the following setup results in nothing opening and a very quick successful exit. Log is pretty sparse as well. I am using the `direnv` supplied shell, but as far as I can tell the environment variables still look good. Hopefully some user error?

* NixOS
* Wayland/Sway

```
$ RUST_LOG=debug cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/notedeck`
2024-12-23T21:36:47.618469Z DEBUG eframe: Using the wgpu renderer    
$ echo $?
0
```

**Comment by jb55** [comment]
I know with x11 I needed:

```nix
let
  x11libs = lib.makeLibraryPath (with xorg; [
  			libX11
  			libXcursor
  			libXrandr
  			libxi
  			libglvnd
  			vulkan-loader
  			vulkan-validation-layers
  			libxkbcommon ]);
in
{
    LD_LIBRARY_PATH = "${x11libs}";
}
```

not sure if wayland needs something similar

**Comment by duck1123** [comment]
Adding `wayland` to that list fixed it for me.
