### ISSUE TITLE
Account Management View desktop design

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#77]
We have a prototype account management view but we don't really have a design yet:

![](https://cdn.jb55.com/s/4584e12b13f8505c.png)

For the sidebar selector, we can keep it simple like tweetdeck does it:

|Side menu click popup|"Manage Accounts"|
|---------------|------------------|
![](https://cdn.jb55.com/s/a2ef44e306d131f8.png)|![](https://cdn.jb55.com/s/67ea26ae2eb1d15f.png)|

It doesn't look like we have a design for this in the figma yet (cc @robagreda ), until then I think we should just copy tweetdeck?

cc @kernelkind

**Comment by jb55** [comment]
if doing the popup is too hard I don't mind creating a new control for this like I did with egui-tabs, since I'm getting the hang of it. all we need is these two views and we can put them into any container-type we want. we don't need to assume a container.

**Comment by kernelkind** [comment]
@jb55 can I get a demonstration of how the side menu user accounts are used? What is the purpose of displaying them individually in the side menu?

**Comment by jb55** [comment]
On Sat, May 18, 2024 at 08:54:14AM GMT, kernelkind wrote:
>@jb55 can I get a demonstration of how the side menu user accounts are
>used? What is the purpose of displaying them individually in the side
>menu?

The idea is that the deck configurations will be nostr notes created and
signed by these pubkeys. When you switch to a new pubkey it will load
their default deck. We can have more than one deck per pubkey via
parameterized replaceable events.

If a user makes their deck public (no encryption), then you can load
other people's decks as well by adding a watch-only account. Perhaps if
there is only an encrypted list it could just have some default view for
that user.

**Comment by kernelkind** [comment]
![account manager](https://github.com/damus-io/notedeck/assets/8139906/58a65f90-6fa6-4cbe-88c6-1adae5d0000a)

**Comment by jb55** [comment]
done
