### ISSUE TITLE
Some font families missing glyphs

### ISSUE THREAD

**Issue by hellodword** [damus-io/notedeck#78]
I noticed it when debugging, as you see, the pop-up window displays well while the main window doesn't:

![image](https://github.com/damus-io/notedeck/assets/46193371/98462fbf-48fc-42e4-a62b-cbdadc6a4000)

And I think it's existing on macOS (upper left corner):

https://github.com/damus-io/notedeck/blob/4fc6e225caacce70042b42fc926429ae96b45736/README.md?plain=1#L11

And the Emojis are not colorful.

I think embedded fonts are required for this.

**Comment by jb55** [comment]
On Fri, May 17, 2024 at 07:51:53PM GMT, hellodword wrote:
>I noticed it when debugging, as you see, the pop-up window displays well while the main window doesn't:
>
>![image](https://github.com/damus-io/notedeck/assets/46193371/98462fbf-48fc-42e4-a62b-cbdadc6a4000)

oh interesting, looks our font configuration differs for some reason,
nice catch. should be an easy fix.

>And the Emojis are not colorful.
>
>I think embedded fonts are required for this.

I don't think embedding fonts is enough, see:

- https://github.com/emilk/egui/issues/2551

Someone just put together egui-swash so I wonder if that will help?

https://github.com/atynagano/egui-swash

**Comment by jb55** [comment]
Split this issue into:

- #91 

Glyph fix in

- #90
